In [5]:
import pandas as pd
df = pd.read_csv("uber-raw-data-apr14[1].csv") # to load data
df.head()# show first rows

          Date/Time      Lat      Lon    Base
0  4/1/2014 0:11:00  40.7690 -73.9549  B02512
1  4/1/2014 0:17:00  40.7267 -74.0345  B02512
2  4/1/2014 0:21:00  40.7316 -73.9873  B02512
3  4/1/2014 0:28:00  40.7588 -73.9776  B02512
4  4/1/2014 0:33:00  40.7594 -73.9722  B02512

In [15]:
df.info() # to understaan the data
df.describe() # to understand basic statistics

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 564516 entries, 0 to 564515
Data columns (total 7 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Date/Time  564516 non-null  datetime64[ns]
 1   Lat        564516 non-null  float64
 2   Lon        564516 non-null  float64
 3   Base       564516 non-null  object
 4   hour       564516 non-null  int32
 5   day        564516 non-null  int32
 6   weekday    564516 non-null  int32
dtypes: datetime64[ns](1), float64(2), int32(3), object(1)
memory usage: 23.7+ MB

,Date/Time,Lat,Lon,hour,day,weekday
count,564516,564516.000000,564516.000000,564516.000000,564516.000000,564516.00000
mean,2014-04-16 17:46:01.296261120,40.740005,-73.976817,14.465043,16.117127,2.86698
min,2014-04-01 00:00:00,40.072900,-74.773300,0.000000,1.000000,0.00000
25%,2014-04-08 16:27:00,40.722500,-73.997700,10.000000,8.000000,1.00000
50%,2014-04-16 19:19:00,40.742500,-73.984800,16.000000,16.000000,3.00000
75%,2014-04-24 22:14:00,40.760700,-73.970000,19.000000,24.000000,4.00000
max,2014-04-30 23:59:00,42.116600,-72.066600,23.000000,30.000000,6.00000
std,NaN,0.036083,0.050426,5.873925,9.048139,1.82081

In [12]:
df.columns

Index(['Date/Time', 'Lat', 'Lon', 'Base'], dtype='object')

In [13]:
df['Date/Time'] = pd.to_datetime(df['Date/Time'])
# to covert to datetime type

In [14]:
df['hour'] = df['Date/Time'].dt.hour
df['day'] = df['Date/Time'].dt.day
df['weekday'] = df['Date/Time'].dt.weekday